### PR TITLE
Fix: modify Serverlessland URL path and update diagram label to WebSocket API

### PR DESCRIPTION
**Pull request by windrichie**
*Issue #, if available:*

*Description of changes:*
- modified API Gateway label to WebSocket and renamed the JSON file

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cornelcroi** [comment]
example-pattern.json is missing. Can you add it please?
 Also, I don't see any modification regarding the URL path.

**Comment by windrichie** [comment]
@cornelcroi the example-pattern.json file is already in the current repo: https://github.com/aws-samples/serverless-patterns/blob/main/apigw-websocket-api-bedrock-streaming/example-pattern.json. That's why it is not in this PR.

For the URL path, I renamed the apigw_lambda_bedrock.json to apigw-websocket-api-bedrock-streaming.json, as I thought that was where the URL path is taken from. In any case, I think `apigw-websocket-api-bedrock-streaming` would be a suitable path.

**Comment by cornelcroi** [comment]
Actually `example-pattern.json` needs to be in the PR as we have a github action that looks for it. Can you just make a mior change so that the file is part of the PR?

**Comment by windrichie** [comment]
got it, made a minor change to example-pattern.json @cornelcroi

**Review by cornelcroi — APPROVED** [review]

**Pull request merged**
