### PR TITLE
New pattern submission- s3 lambda dotnet

### PR DESCRIPTION
**Pull request by gtmjohnson**
Issue #1471, New pattern submission s3-lambda-dotnet

Adding new pattern for .NET Lambda - this template uses SAM to deploy a .NET 6 Lambda function, an S3 bucket, and IAM resources required to run the application. The lambda function consumes ObjectCreated events from the S3 bucket and the code takes uploaded images, resizes them into thumbnails, and writes to a new folder in the S3 bucket.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by gtmjohnson** [comment]
> @gtmjohnson your 'example-pattern.json' is missing some key fields, please review below and address any errors you have
> 
> 1. `language`: language is not one of enum values: TypeScript,Node.js,Python,Java,Go,Rust,.NET,OpenAPI,YAML,
> 
> _If you need any help, take a look at the [example-pattern file](https://github.com/aws-samples/serverless-patterns/blob/main/_pattern-model/example-pattern.json)._
> 
> Make the changes, and push your changes back to this pull request. When all automated checks are successful, the Serverless DA team will process your pull request.

Changed C# to .NET, which should fix the error

**Comment by singledigit** [comment]
This is not a good fit for the Serverless Land patterns collection. We have plenty of patterns the demonstrate S3 to a Lambda function. The advantage of this is the code and how to do it in .Net 6. I recommend changing this to either a:

repo: https://serverlessland.com/repos

or

snippret: https://serverlessland.com/snippets

Closing this PR.

**Comment by singledigit** [comment]
Additionally, if you go forward with the repo, please remove the bucket name parameter. It is not rquired and without it, CloudFromation will create a unique bucket name every time.

**Review by singledigit — CHANGES_REQUESTED** [review]
Remove requirement for bucket name and let CFN name the bucket

**Review by singledigit — APPROVED** [review]

**Pull request merged**
