### PR TITLE
Added several patterns into a new category "Terraform (with modules)"

### PR DESCRIPTION
**Pull request by antonbabenko**
## Description of changes:

Unfortunately, it is not easy for me to split this PR into smaller ones because it also introduces some shared files. The next PRs will be significantly smaller.

Please review the code in any of the patterns folders (`terraform-*`), and I will be able to apply the proposed changes across other folders as necessary.

## Patterns:

- [] terraform-apigw-http-lambda
- [ ] terraform-dynamodb-streams-lambda
- [ ] terraform-eventbridge-scheduled-lambda
- [ ] terraform-lambda-layer
- [ ] terraform-s3-lambda
- [ ] terraform-s3-object-lambda
- [ ] terraform-sqs-lambda

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution under the terms of your choice.

### CODE REVIEW

**Comment by boyney123** [comment]
Hey @antonbabenko , thanks for the pull request, great to see all these patterns!

Going to take me some time to review, but just to let you know I have started! 👍

**Comment by boyney123** [comment]
Hey @antonbabenko ,

Thanks again, just been through the code, mostly looking good to me! I have a few questions maybe you can help me understand.

1. `terraform-fixtures/docker/Dockerfile` is this used anywhere in your patterns? Not sure I can see anywhere, or mentioned in docs? What is it doing exactly (just to help me understand)
2. `python_src.zip` is there a reason this is included in the terraform-fixtures?

Everything else looking good to me

**Comment by antonbabenko** [comment]
@boyney123 Thank you for the quick review!

You're right that both of these files in `terraform-fixtures` are not in use. I have removed them.

`python_src.zip` can be handy to use packaged lambda function instead of packaging it every time as I do in all patterns where the Lambda module is used. I will be able to add those files later if necessary.

**Comment by boyney123** [comment]
Thank you @antonbabenko , for fast reply.

Looking good to me mate, I will merge these in and get them into SL.

I will ping back here with all the new links when it's done and verified :)

**Comment by boyney123** [comment]
Hey @antonbabenko 

Just to let you know your new section and patterns are live 😍 
https://serverlessland.com/patterns?framework=Terraform+%28with+modules%29

Thanks a lot for making this happen, and hopefully provides value to other serverless folks! Nice work 🙏

**Pull request merged**
