### PR TITLE
New serverless pattern - Access Bedrock via API Gateway with Cognito User Management

### PR DESCRIPTION
**Pull request by Inthuson**
*Issue #, if available:* #2065

*Description of changes:*
This pattern creates an AWS CDK Python application to access Bedrock via API Gateway with Cognito user management, domain restriction, API request throttling, and quota limits.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Inthuson** [comment]
example-pattern.json has been named as apigw-bedrock-cognito-cdk-pattern.json

**Comment by pputhran** [comment]
@Inthuson thanks for the submission. example-pattern.json is a required file. Can you please either rename apigw-bedrock-cognito-cdk-pattern.json to example-pattern.json OR copy over the contents from apigw-bedrock-cognito-cdk-pattern.json to example-pattern.json ?

**Comment by Inthuson** [comment]
@pputhran - renamed the file to example-pattern.json

**Comment by Inthuson** [comment]
Removed LinkedIn URL

**Review by pputhran — APPROVED** [review]

**Pull request merged**
