### PR TITLE
New Serverless Patterns - Lambda extesion to retrieve SSM and Secrets Values from PHP Lambda on CDK

### PR DESCRIPTION
**Pull request by rafaelbernard**
*Description of changes:*

[The use of Lambda Extensions to retrieve SSM Parameter Store and Secrets Manager values for PHP Lambdas using CDK](https://github.com/aws-samples/serverless-patterns/issues/2322).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cornelcroi** [comment]
The PR includes modifications to several patterns. I'm not sure if this was your intention.
Could you please exclude all other changes and retain only those related to "Lambda extension to retrieve SSM and Secrets Values from PHP Lambda"?

**Comment by rafaelbernard** [comment]
> The PR includes modifications to several patterns. I'm not sure if this was your intention. Could you please exclude all other changes and retain only those related to "Lambda extension to retrieve SSM and Secrets Values from PHP Lambda"?

Thanks for reviewing it.

That was not my intention. I apologise. I have removed all unrelated changes.

**Comment by ellisms** [comment]
Hi @rafaelbernard . Thanks for the submission. Since this is a Lambda extension, I think it fits better in the [aws-lambda-extensions](https://github.com/aws-samples/aws-lambda-extensions/blob/ad2aceeb9f6e59ca1e6a5bf04197ca9009cb2458/CONTRIBUTING.md) repo. I recommend resubmitting it there.

**Comment by rafaelbernard** [comment]
> Hi @rafaelbernard . Thanks for the submission. Since this is a Lambda extension, I think it fits better in the [aws-lambda-extensions](https://github.com/aws-samples/aws-lambda-extensions/blob/ad2aceeb9f6e59ca1e6a5bf04197ca9009cb2458/CONTRIBUTING.md) repo. I recommend resubmitting it there.

Hi @ellisms , thanks for reviewing it. While reviewing [aws-lambda-extensions](https://github.com/aws-samples/aws-lambda-extensions/blob/ad2aceeb9f6e59ca1e6a5bf04197ca9009cb2458/CONTRIBUTING.md) repo, it seems to be that it holds examples of creation of extensions, which is not the purpose of this PR.

This PR is to apply the pattern of using an existent lambda extension into a PHP lambda using CDK.

**Pull request closed without merging**
