### PR TITLE
New serverless pattern - API Gateway to Lambda to Redshift Serverless over Redshift Data API

### PR DESCRIPTION
**Pull request by mfwahid**
*Issue #, if available:*

*Description of changes:*
This pattern explains how to deploy a Data piepline with Amazon API Gateway (HTTP API), AWS Lambda and Amazon Redshift Serverless

This pattern is useful to accept and respond to requests quickly but offloading the processing as asynchronous process. Once the data ingestion / DDL / query request is made to the API Gateway HTTP API the query will be presented to Redshift Serverless workgroup through Redshift DataAPI. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jbesw** [comment]
This pattern failed template verification - pls see errors and submit a new PR.

**Comment by boyney123** [comment]
Looks like CFN nag has picked up an issue with your template file. Can you have a look and make the relevant changes?

```
[
    {
        "filename": "/usr/src/app/apigw-lambda-redshift-serverless-dataapi/template.yaml",
        "violationsWithErrors": [
            {
                "id": "F3",
                "name": "IamRoleWildcardActionOnPermissionsPolicyRule",
                "type": "FAIL",
                "message": "IAM role should not allow * action on its permissions policy",
                "logical_resource_ids": [
                    "LambdaExecutionRole"
                ],
                "line_numbers": [
                    139
                ],
                "element_types": [
                    "resource"
                ]
            }
        ]
    }
]
```

**Comment by mfwahid** [comment]
> Looks like CFN nag has picked up an issue with your template file. Can you have a look and make the relevant changes?
> 
> ```
> [
>     {
>         "filename": "/usr/src/app/apigw-lambda-redshift-serverless-dataapi/template.yaml",
>         "violationsWithErrors": [
>             {
>                 "id": "F3",
>                 "name": "IamRoleWildcardActionOnPermissionsPolicyRule",
>                 "type": "FAIL",
>                 "message": "IAM role should not allow * action on its permissions policy",
>                 "logical_resource_ids": [
>                     "LambdaExecutionRole"
>                 ],
>                 "line_numbers": [
>                     139
>                 ],
>                 "element_types": [
>                     "resource"
>                 ]
>             }
>         ]
>     }
> ]
> ```

Modified the permission policy and checked in the code.

**Comment by jbesw** [comment]
Due to the large amount of custom code in this solution, I would recommend submitting as a repo instead at https://serverlessland.com/repos.

**Comment by mfwahid** [comment]
Can you please help me with the Github link for repos ?

**Pull request closed without merging**
