### PR TITLE
Add pattern for Step Function HTTP Endpoint task with SAM

### PR DESCRIPTION
**Pull request by andmoredev**
This patterns create a Step Function, the Step Function execution role and an EventBridge Connection using SAM.  
The Step Function will call the OpenWeather API with the new HTTP Endpoint task.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by parikhudit** [comment]
@andmoredev thanks for the PR, however there's a similar pattern existing : https://github.com/aws-samples/serverless-patterns/tree/main/stepfunctions-httpendpoint-sam. I'd suggest enhancing existing pattern rather than having a similar one.

**Comment by andmoredev** [comment]
> @andmoredev thanks for the PR, however there's a similar pattern existing : https://github.com/aws-samples/serverless-patterns/tree/main/stepfunctions-httpendpoint-sam. I'd suggest enhancing existing pattern rather than having a similar one.

@parikhudit while I see it in the code you've shared, I do not see that pattern in https://serverlessland.com/patterns, which is where I tried to see if it already existed.

Can you verify if it actually made it to the website?

**Comment by parikhudit** [comment]
> > @andmoredev thanks for the PR, however there's a similar pattern existing : https://github.com/aws-samples/serverless-patterns/tree/main/stepfunctions-httpendpoint-sam. I'd suggest enhancing existing pattern rather than having a similar one.
> 
> @parikhudit while I see it in the code you've shared, I do not see that pattern in https://serverlessland.com/patterns, which is where I tried to see if it already existed.
> 
> Can you verify if it actually made it to the website?

@andmoredev thanks for checking. So as the code was recently merged it will now added to serverlessland.com soon. I believe you can still add to that pattern via your PR if you wish.

**Comment by parikhudit** [comment]
Closing it due to inactivity. Feel free to reply or reopen it.

**Pull request closed without merging**
