### PR TITLE
New serverless pattern - RDS instance event subscriptions to SNS (Terraform)

### PR DESCRIPTION
**Pull request by MakendranG**
*Issue https://github.com/aws-samples/serverless-patterns/issues/1418, if available:*

*Description of changes:*

This terraform template configures an event subscription for failure, low storage, and availability event categories for RDS Instances.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jbesw** [comment]
This submission includes files from another submission. Please resubmit the PR only with the files for this pattern.

**Comment by jbesw** [comment]
Also, please verify your example-pattern.json file since this has failed validation.

**Comment by MakendranG** [comment]
@jbesw 

In this PR, it have three files which all are required. Which files need to be removed ?

> Also, please verify your example-pattern.json file since this has failed validation.

I have validated the example json file. It have required parameters. In the schema validation failure, I have checked it but there is no specific error mentioned to fix it. Kindly help what need to be fixed here.

**Comment by boyney123** [comment]
> @jbesw
> 
> > This submission includes files from another submission. Please resubmit the PR only with the files for this pattern.
> 
> There are only three files in it which is a terraform file, a readme and example json file. All three files are required. The another submission is for cloudformation.

From what I can tell there are two patterns here? One for SAM and Terraform.

Could you raise them as separate PR for us to review please? That way our automated systems can pick up your pattern and check your pattern file, and it's easier for us to review going forward. Thanks.

**Comment by MakendranG** [comment]
@jbesw 

Thanks for the update.
As per the request, I have removed SAM pattern. This PR will be for terraform. Automated system have picked the pattern and validated. Now it is waiting for approval. Kindly do the needful.

**Comment by MakendranG** [comment]
@jbesw @boyney123 @mavi888 

Requested changes have been done.

**Pull request merged**
