### PR TITLE
New serverless pattern - eventbridge-pipes-ddb-stream-apigateway-iot-core-cdk

### PR DESCRIPTION
**Pull request by MajdSoufan**
*Issue #1274*

*Description of changes:*

This project contains a sample AWS Cloud Development Kit (AWS CDK) template for deploying a DynamoDb Table with a Stream configured to an EventBridge Pipe. Items data tunneled through Pipe will target an API Gateway endpoint that uses AWS direct integration to publish the a message to a pre-configured IoT Core Topic with the item data.

This pattern follows a _functionless_ approach to achieve a full-circle event propagation, and report the change back to the client.

The following resources will be provisioned:

- A DynamoDB Table that stores data and configured with a DDB Stream
- An EventBridge Pipe configured as a target for the DDB Stream
- A REST Api configured as a target for the EventBridge Pipe
- The REST Api configures a path `iot` with a POST request and an AWS Direct Service Integration to IoT Data
- An IoT Core Topic & IoT Core Endpoint to publish data to

IoT Core is an AWS service that covers a wide verity of use cases. One important feature that can be leveraged in serverless event driven architectures, is the scalable pub/sub topic based api.

NOTICE: the pattern doesn't use AWS Lambda at any stage to propagate the data change

**_Disclaimer:_** This pattern doesn't favor one architectural pattern over another. It is merely an example of using _functionless_ development with IoT Core

### CODE REVIEW

**Comment by MohamadSoufan** [comment]
@mavi888 can you help with this schema validation issue?
When I go to the `Actions` tab, I see 2 runs for my repo, one succeeded and one failed!
I believe the failure is happening because on line `37` of  the `validate.js` file the script can't find my `example-pattern.json` as its being added as follows `eventbridge-pipes-ddb-stream-apigateway-iot-core-cdk/example-pattern.json` not at the most upper level

Not sure what the issue is here!
Appreciate the help

**Comment by MajdSoufan** [comment]
@mavi888 Can you check the pipelines please? I think they are awaiting manual approval

**Comment by MajdSoufan** [comment]
@mavi888 I have fixed the typo error in example-patterns.json

**Comment by MajdSoufan** [comment]
@mavi888 I think the github actions are awaiting an approval. Can you trigger that?

**Comment by MajdSoufan** [comment]
@mavi888 Can you approve the pipeline please?

**Comment by MajdSoufan** [comment]
@mavi888 the workflow requires manual approval. Can you approve the pipeline please?

**Comment by mavi888** [comment]
Thanks for submitting this pattern. 
I wonder if this is a pattern or an application? I think this is quite a complex solution for a pattern, if you think that this can be its own app think about sharing it instead as a repo: https://serverlessland.com/repos

but if you want to continue as a pattern there are a couple of things:
- 1 please add an image to showcase the architecture you are building this is a complex pattern as i said before
- the deployment instructions should include the fetching of the iot topic endpoint before deploying... if not this doesnt work. Please fix

**Comment by mavi888** [comment]
besides that this pattern is well documented and everything looks good. 
so when that is added i will merge it

**Comment by MohamadSoufan** [comment]
Thanks @mavi888 for the notes
We do think its a pattern that links Dynamo, EB Pipes, API Gateway & IoT Core together
I have included instructions on how to fetch the iot topic endpoint under the #input section in the README.md but i can also add that to the deployment instructions
I will work on adding an image to showcase the architecture and we can discuss further.
The pattern is complex in terms of how many services are involved but we still think its a pattern because its repeatable and can be reused in different scenarios 

Will add additional details in our next commits

**Comment by MajdSoufan** [comment]
@mavi888 anything preventing us from merging this new patter?

**Comment by MohamadSoufan** [comment]
> Thanks for submitting this pattern. I wonder if this is a pattern or an application? I think this is quite a complex solution for a pattern, if you think that this can be its own app think about sharing it instead as a repo: https://serverlessland.com/repos
> 
> but if you want to continue as a pattern there are a couple of things:
> 
> * 1 please add an image to showcase the architecture you are building this is a complex pattern as i said before
> * the deployment instructions should include the fetching of the iot topic endpoint before deploying... if not this doesnt work. Please fix

Hello @mavi888 I have just pushed a change addressing the notes in this comment
Let me know if there is anything else I need to change

Thanks

**Comment by MohamadSoufan** [comment]
> Thanks for submitting your pattern. This pattern was merged and you can see and share the pattern using this link https://serverlessland.com/patterns/eventbridge-pipes-ddb-stream-apigateway-iot-core-cdk
> 
> Thanks a lot!

You are very welcome @mavi888 and we both are delighted to be part of this community!

There was an issue with the LinkedIn links, I think we just should put `/mohamad-soufan/` instead of the entire https link
Can I open a new PR for that?
Thanks

**Pull request merged**
