### PR TITLE
New Serverless Patterns - Image Compression and Custom Notification upon alarm state change

### PR DESCRIPTION
**Pull request by aroradev-dms**
Added Serverless Pattern for Image Compression and Custom Notification upon alarm state change

1. Image Compression : This pattern leverages the AWS Lambda and S3 event notifications to compress a high quality image from a source bucket to a destination bucket.

2.  Custom Notification upon alarm state change : As we might be aware that notification through CloudWatch Alarm-SNS can not be modified, This pattern focuses on customizing the notifications by leveraging Lambda function. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by singledigit — CHANGES_REQUESTED** [review]
@aroradev-dms, the best practice is to let CloudFormation name the buckets instead of passing in a Bucket name. Is there a reason we need to on this?

**Comment by aroradev-dms** [comment]
> @aroradev-dms, the best practice is to let CloudFormation name the buckets instead of passing in a Bucket name. Is there a reason we need to on this?

CloudFormation naming the buckets will have same bucket name, thereby asking the users to enter their own source and destination bucket name.

**Comment by singledigit** [comment]
That is actually incorrect. CFN will auto assign a unique name. There is no reason for the user to do this as they are more likely to have a name space collision. Please update.

**Comment by jbesw** [comment]
Hello, this example is more of a solution of a pattern, due to including image compression. I'd recommend implement Eric's fix but submitting to the Serverless Repos instead (https://serverlessland.com/repos).

**Pull request closed without merging**
