### PR TITLE
New serverless pattern - cloudwatch-sns-secretsmanager

### PR DESCRIPTION
**Pull request by jainam1992**
*Issue #, if available:* #1199

*Description of changes:* This pattern explains how to deploy a SAM application that Detects and Notify on Amazon Secrets Manager Secret Key Creation, Updation and Deletion using Amazon CloudWatch event and Amazon SNS

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jbesw** [comment]
Your example-pattern.json file has failed validation - please fix this and we will reevaluate the submission.

**Comment by jainam1992** [comment]
Hello @jbesw , The example-pattern.json seems valid. It does contain a valid JSON.  The error shows "SNS topic policy should not allow * principal". But this is required for the flow to work. User can change policy based on their requirement. Can you please check again? Thank you.

**Comment by jainam1992** [comment]
@bls20AWS Hello Ben.  Is this pattern already published on Serverlessland ? If yes, can you please provide me link to it? Thank You.

**Comment by jainam1992** [comment]
@bls20AWS Hey Ben. I can see pattern published now - https://serverlessland.com/patterns/cloudwatch-secrets-manager-sam  . However, diagram seems incorrect. There is no Lambda function in this flow.  The code and pattern looks correct but Lambda needs to be removed from the diagram. Thank you

**Pull request merged**
