### PR TITLE
Added api-sqs-lambda-python serverless pattern

### PR DESCRIPTION
**Pull request by aadianil**
*Issue #, if available:*

*Description of changes:* Added api-sqs-lambda-python serverless pattern

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aadianil** [comment]
Hello David! Can you please approve this pull request? Thank you.

**Comment by jbesw** [comment]
Patterns should contain minimal custom code and not include zip files. Additionally, the pattern validation is still failing. Please change the PR and we can reevluate.

**Comment by aadianil** [comment]
> Contributor

**Comment by aadianil** [comment]
Hello James! I have reduced the number of characters to below 75 in the profile picture link inside event-patterns file and also we need the index.zip file as we cannot deploy the .py file using SAM.

I have also tested and re-deployed the stack using SAM and it is working fine now. Kindly check and update.

**Comment by boyney123** [comment]
Thanks, sorry it took so long to merge, looks like this PR feel through our PR review stuff. Sorry about that. Thanks for the contribution!

**Pull request merged**
