### PR TITLE
Added example-pattern.json

### PR DESCRIPTION
**Pull request by shankey28**
*Added example-pattern.json*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shankey28** [comment]
@boyney123  Please advise on this PR.

**Comment by shankey28** [comment]
Updated example-pattern.json

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

**Comment by shankey28** [comment]
@bls20AWS  Can you please check here? This has been pending for a while now.

**Comment by boyney123** [comment]
Thanks @shankey28 for the patience.

They code for the pattern itself is missing? You need to commit then code in this pull request for the pattern, unless I'm missing something here?

**Comment by boyney123** [comment]
Still only  2 files changed? Have you pushed the changes?
image

**Comment by shankey28** [comment]
@boyney123 some goofiness going on. Hopefully 3rd time is a charm.

**Comment by boyney123** [comment]
Thanks! Now your example-pattern file is missing it seems?

**Comment by shankey28** [comment]
Added example-pattern.json file back.

**Comment by shankey28** [comment]
@boyney123  Any update?

**Comment by boyney123** [comment]
Thank you for your patience @shankey28 , reviewed and merged. Thanks for the PR

**Pull request merged**
