### PR TITLE
feat(CloudTrial log streaming to OpenSearch Serverless): CDK to deplo…

### PR DESCRIPTION
**Pull request by rupeshtiwari**
…y Cloudtrail to OpenSearch Serverless

Python CDK sample to deploy lambda and Amazon OpenSEarch Serverless to stream cloud trail logs

*Issue #, if available:*

*Description of changes:*
New CDK sample written in python to stream cloud trail log using AWS lambda and index in Amazon OpenSearch Serverless. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by singledigit — CHANGES_REQUESTED** [review]
This pattern is missing the `example-pattern.json` file used for automation. Pease see the pattern submission found at https://github.com/aws-samples/serverless-patterns/issues/new?assignees=jbesw&labels=&template=new-serverless-pattern-submission.md&title=New+pattern+submission

**Comment by singledigit** [comment]
Hi @rupeshtiwari we still need the example-pattern.json file before we can merge.

**Comment by rupeshtiwari** [comment]
> Hi @rupeshtiwari we still need the example-pattern.json file before we can merge.

Thank you and apologize for the delay, I added the example-pattern.json please do the needful.

**Comment by rupeshtiwari** [comment]
Hi @singledigit can you please review and approve this pull request let me know what else you need from me?

**Comment by rupeshtiwari** [comment]
Hi @singledigit  in this [serverlessland site](https://serverlessland.com/patterns) I do not see my pattern listed how many days it takes to refresh this site with the new patterns? https://serverlessland.com/patterns

**Comment by singledigit** [comment]
The pattern went out this morning. https://serverlessland.com/patterns/cloudtrail-streaming-to-opensearch-serverless-cdkSent from my iPhoneOn Jun 2, 2023, at 2:26 PM, Rupesh Tiwari ***@***.***> wrote:﻿
Hi @singledigit  in this serverlessland site I do not see my pattern listed how many days it takes to refresh this site with the new patterns? https://serverlessland.com/patterns

**Pull request merged**
