### PR TITLE
cdk-appsync-sns

### PR DESCRIPTION
**Pull request by mtliendo**
Update to showcase L2 construct and AppSync JS functions in a pipeline

### CODE REVIEW

**Comment by mavi888** [comment]
It would be great if the testing part of the README included how to verify that this worked. Now it says that it publishes to SNS, but how i know ? How i can see the message?

**Comment by mtliendo** [comment]
Updated with `example-pattern.json`. @mavi888 The request from AppSync to SNS returns the [SNS messageId](https://github.com/aws-samples/serverless-patterns/blob/main/cdk-appsync-sns/console.png) to verify that SNS received the message. Does that work or is there another form you're looking for?

**Comment by mtliendo** [comment]
I'm sure it's something small, but I could use another pair of eyes on why the `example-pattern.json` isn't successfully validating 🙏🏽

**Comment by mavi888** [comment]
I will merge this pattern, but I think you can add more value by explaining a bit more in the readme what is going on.

**Comment by mavi888** [comment]
Thanks for submitting your pattern.
Now this pattern is public in Serverless land

https://serverlessland.com/patterns/cdk-appsync-sns

You can share your pattern using this link :)

**Pull request merged**
