### PR TITLE
New Serverless pattern: websocket api to SNS with request validation

### PR DESCRIPTION
**Pull request by bharat-aws**
New Serverless pattern: websocket api to SNS with request validation

*Issue #, if available:*

*Description of changes:*
new pattern to integrate websocket API with SNS with request validation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by boyney123** [comment]
Hi @bharat-aws 

There is no files in your PR? Maybe missing something here?

**Comment by bharat-aws** [comment]
hi, apologies for the confusion. i merge my work branch with my main branch, you should see the changes now

**Comment by bharat-aws** [comment]
is there any ETA on when this PR will be evaluated?

**Comment by boyney123** [comment]
Thanks @bharat-aws , just checked will merge this in

**Comment by bharat-aws** [comment]
i see validate-pattern  failed for this merge. also the serverlessLand article is not published as well. can you share how can we resolve it?

**Pull request merged**
