### PR TITLE
New serverless pattern - cloudwatch-logs-subscription-lambda-sam

### PR DESCRIPTION
**Pull request by omarrosadio**
*Issue #, if available:*

*Description of changes:*
A new pattern is added in the folder cloudwatch-logs-subscription-lambda-sam

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by singledigit — CHANGES_REQUESTED** [review]
This pattern does not pass the validation of the `example-pattern.json` file. Please correct and update.

**Review by omarrosadio — COMMENTED** [review]
fix - validation pattern

**Review by singledigit — APPROVED** [review]

**Comment by singledigit** [comment]
This still is not passing the validation test. @boyney123 can you help us out here?

**Comment by omarrosadio** [comment]
fix - language property in example-pattern.json file

**Pull request merged**
