### PR TITLE
New serverless pattern - apigw-sqs-rest

### PR DESCRIPTION
**Pull request by mfwahid**
*Issue #, if available:*

*Description of changes:*
This pattern creates an Amazon API Gateway (REST API) with a send route that send message to a SQS queue

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mfwahid** [comment]
Hi,

Reaching out to see if there is any action item on me. 

Thanks,
Abdul Waheed

**Comment by jbesw** [comment]
This pattern has failed template validation.

**Comment by mfwahid** [comment]
Can you please help me what is the bug and what change is required ?

**Comment by jbesw** [comment]
This will be live at https://serverlessland.com/patterns/apigw-sqs-sam shortly.

**Pull request merged**
