### PR TITLE
Apigw lambda dynamodb python cdk

### PR DESCRIPTION
**Pull request by rupeshtiwari**
*Issue #, if available:*

*Description of changes:*
Python CDK sample for creating AWS Lambda inside VPC and accessing DynamoDb table using VPC Endpoint. Lambda is being invoked by API Gateway REST API. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jbesw** [comment]
Hello - this is missing the example-pattern.json metadata file. Please add so we can test and merge.

**Comment by rupeshtiwari** [comment]
> Hello - this is missing the example-pattern.json metadata file. Please add so we can test and merge.

How to upload the architecture diagram to `https://serverlessland.s3.amazonaws.com/`??

**Comment by rupeshtiwari** [comment]
> Hello - this is missing the example-pattern.json metadata file. Please add so we can test and merge.

I have added the example-pattern.json file. I apologize I was not aware that this file is required thanks.

**Comment by rupeshtiwari** [comment]
Hi @jbesw please let me know what else you need from me. @jbesw

**Comment by rupeshtiwari** [comment]
Hi @jbesw , @boyney123  can you please review and approve this pull request let me know what else you need from me?

**Comment by jbesw** [comment]
Reviewing this pattern, why is the Lambda function in a VPC? The VPC configuration is not necessary to insert into DynamoDB.

**Comment by rupeshtiwari** [comment]
Thank you, @jbesw , for taking the time to review this. I've noticed that many financial customers tend to provision their lambda functions and databases within a Virtual Private Cloud (VPC) for compliance purposes. They typically expose their services through API Gateway. Recently, I assisted a customer in implementing this architecture in their project, and I believe this experience could prove valuable for other customers facing similar requirements.

**Pull request merged**
