### PR TITLE
Code for Chat-with-slack-channel

### PR DESCRIPTION
**Pull request by TanyaGupta23**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by TanyaGupta23** [comment]
I have uploaded the example-pattern.json file

**Comment by julianwood** [comment]
Please can you include some more information in the README on how to deploy the pattern and test it. You can link to the external instructions but currently a reader doesn't know how to get started with actually using this pattern.
Also, we prefer using AWS SAM for the deployment. Please check whether `sam deploy` works when deploying this.

**Comment by TanyaGupta23** [comment]
Made the changes as suggested. Please check

**Comment by boyney123** [comment]
Going to close for now, feel free to re-open once @julianwood comments been addressed, thanks

**Pull request closed without merging**
