### PR TITLE
Node.js Lambda function configured to use ESM Modules

### PR DESCRIPTION
**Pull request by lucamezzalira**
*Issue #, if available:*

*Description of changes:*
I've created a template for Lambda functions using Node.js with ESM modules and TypeScript with AWS CDK.
There are a few configurations that has to be applied in order to get ESM modules properly configured with TypeScript so this is an "Hello World" template that provides the basics configuration to start a new API leveraging ESM modules.
The ESBuild configuration in CDK provides already optimizations such as tree-shaking and minification that are not defined out of the box otherwise.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mavi888** [comment]
This pattern is not following the guidelines for patterns in serverless land. please refer to the [example pattern](https://github.com/aws-samples/serverless-patterns/tree/main/_pattern-model) and follow the instructions. For starters a README file and a pattern file are missing.

**Comment by lucamezzalira** [comment]
Thanks! I'll update accordingly :)

**Comment by lucamezzalira** [comment]
@mavi888 I've uploaded the metadata using the json template and I've updated the README file as requested.
Let me know if there is anything else I should review

thanks in advance

**Comment by jbesw** [comment]
Thanks - this will be live at serverlessland.com/patterns/lambda-node-esm-cdk shortly.

**Pull request merged**
