### PR TITLE
New pattern - AWS API Gateway to Amazon Kinesis 

### PR DESCRIPTION
**Pull request by brittanyly**
Description of changes:
This pattern creates an Amazon API Gateway REST API that integrates with an Amazon Kinesis data stream using AWS Cloud Development Kit (AWS CDK) in Typescript.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jbesw** [comment]
This example is missing the example-pattern.json metadata file. Pls add this so we can test and merge.

**Comment by brittanyly** [comment]
example-pattern.json added

**Comment by MudassarBashir** [comment]
@jbesw @julianwood PR appears to be passing checks now. Please advise if any other changes are needed. Thank you!

**Comment by jbesw** [comment]
Thanks - this will be live at https://serverlessland.com/patterns/apigw-kinesis-typescript-cdk shortly.

**Pull request merged**
