### PR TITLE
APIGW-Kinesis-Integration

### PR DESCRIPTION
**Pull request by vaidehip86**
*Issue #, if available:*

*Description of changes:*

Adding a new pattern for API Gateway Kinesis Data stream integration using SAM.

### CODE REVIEW

**Review by singledigit — CHANGES_REQUESTED** [review]
This does not conform to the required template format. Please add the example-pattern.json file and update.

**Comment by vaidehip86** [comment]
Added example-pattern.json file

**Comment by vaidehip86** [comment]
Hi @singledigit @boyney123 , I have added example-pattern.json file, can you please take a review ?

**Comment by vaidehip86** [comment]
Hi @singledigit and @boyney123 I have added the missing example-pattern.json, can you please review now?

**Pull request merged**
