### PR TITLE
New serverless pattern: s3 trigger fargate task

### PR DESCRIPTION
**Pull request by jeromevdl**
*Issue #, if available:* #2378

*Description of changes:*

Adding a new pattern: S3 -> EventBridge -> Fargate, using CDK / Typescript

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by ellisms — CHANGES_REQUESTED** [review]
@jeromevdl Thanks for the submission. Requesting a few minor changes.

**Comment by ellisms** [comment]
@jeromevdl Were you able to review my comments and make changes?

**Comment by jeromevdl** [comment]
I completely missed the notification, will have a look, thanks for the reminder

**Comment by jeromevdl** [comment]
there's still requested changes, but I see nothing to change in the discussion...

**Review by ellisms — APPROVED** [review]

**Comment by ellisms** [comment]
Sorry, I didn't approve them. They are now approved and this is in the queue to publish.

**Pull request merged**
