### PR TITLE
New serverless pattern - cdk-apigw-lambda-dynamodb-serverless

### PR DESCRIPTION
**Pull request by iAmSherifCodes**
Issue #, if available:

Description of changes:
This project is a new pattern that consists of API Gateway, AWS Lambda, and Amazon DynamoDB built with AWS CDK.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ellisms** [comment]
Thanks for the submission @iAmSherifCodes. It looks like this PR will delete an existing Python-SAM pattern in `apigw-lambda-dynamodb` in commit `e6960792213bb400f303b114b1cc9734c66bf22f`. We cannot merge this request with the delete. Recommend you reverse that commit first.

**Comment by iAmSherifCodes** [comment]
Thank you for the feedback @ellisms, Kindly review the recent changes.

**Comment by ellisms** [comment]
Hi @iAmSherifCodes I still see the files deleted from `apigw-lambda-dynamodb` and I think this will delete the existing pattern with that name. Can you create a new branch and cherry pick just your new changes?

**Comment by ellisms** [comment]
Closing since this appears stale. Feel free to reopen after making the suggested changes.

**Pull request closed without merging**
