### PR TITLE
New serverless pattern - eventbridge-pipes-kinesis-to-timestream

### PR DESCRIPTION
**Pull request by aayushwadhwa**
*Issue*
https://github.com/aws-samples/serverless-patterns/issues/2320

*Description of changes:*

This commit adds a new pattern to ingest data into a Timestream table from Kinesis streams using EventBrigde Pipes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ellisms** [comment]
@aayushwadhwa Thanks for the submission. Requesting a few minor edits before we proceed.

**Comment by aayushwadhwa** [comment]
@ellisms I'm not able to see your comments on this request. Can you check if those were published?

**Review by ellisms — CHANGES_REQUESTED** [review]

**Comment by ellisms** [comment]
Sorry about that. Just published the review.

**Comment by ellisms** [comment]
@aayushwadhwa Checking in to see if you are making these edits.

**Comment by ellisms** [comment]
Closing since this appears stale. Feel free to reopen after making the suggested changes.

**Pull request closed without merging**
