### PR TITLE
adding auth0 to api dest examples

### PR DESCRIPTION
**Pull request by PurpleAmyr**
*Issue #, if available:*

*Description of changes:*
adding Auth0 integration to examples for API Destinations

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ellisms** [comment]
Hi @PurpleAmyr - following up on this PR. The example-pattern.json file is invalid. Once corrected, I can move forward with reviewing.

**Comment by ellisms** [comment]
@PurpleAmyr I tried testing this and the rule fails to invoke. Can you take a look?

**Comment by singledigit** [comment]
Monitoring for a gaurdian approved pattern. @ellisms just let me know.

**Comment by singledigit** [comment]
@PurpleAmyr any updates on this?

**Comment by PurpleAmyr** [comment]
Hello! I was out for the last 2 weeks i apologize.
@ellisms did you test it with the following code? (testEvent.Json)
https://github.com/aws-samples/serverless-patterns/pull/2018/commits/55717bf7ceac145b8c3b161a7b40f71d6df73876#diff-63d67cd9abbac47667f94a5dbb602f2f360ba681c548fa2311c3f6ed690992bb
When inputing it into the architecture through the console, the user appeared in the auth0 database.

**Comment by ellisms** [comment]
Hi @PurpleAmyr  - yes, I ran 
`aws events put-events --entries file://testEvent.json`
The EB rule has an invocation failure, and the error sent to the DLQ is: 
`
ApiDestination returned HTTP status 404 with payload: {"error":"connection not found"}
`
 The connection has a status of Authorized in the console.

**Comment by singledigit** [comment]
Hey @ellisms and @PurpleAmyr if we can't get this resolved in the next week or so, let's close it.

**Pull request closed without merging**
