### PR TITLE
Updating Existing Pattern - apigw-s3-proxy

### PR DESCRIPTION
**Pull request by vamsipulikonda**
*Issue #, if available:* #2427

*Description of changes:*
Hello Team,
I am creating this to update the Existing Serverlessland pattern - https://serverlessland.com/patterns/apigateway-rest-s3-sam.

With an existing patter, user can only read files inside the root folder of S3 but with the updated pattern, user would be able to read files inside folder and sub-folder.

Creating this as per pputhran suggestion over the issue - https://github.com/aws-samples/serverless-patterns/pull/2410

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by bfreiberg — COMMENTED** [review]
Looks good, one minor issue before it's good to go

**Comment by vamsipulikonda** [comment]
Hello Team,
Any update or ETA on Pattern Update

**Comment by vamsipulikonda** [comment]
Hello Team,
Thanks for commiting the changes, but my photo and details are yet not updated in the pattern.
https://serverlessland.com/patterns/apigateway-rest-s3-sam

**Comment by vamsipulikonda** [comment]
Hello Team,
Thanks for commiting the changes, but my photo and details are yet not updated in the pattern.
https://serverlessland.com/patterns/apigateway-rest-s3-sam

**Comment by vamsipulikonda** [comment]
My bad, its wrong URL which I was looking at.
https://serverlessland.com/patterns/apigw-s3-proxy

**Pull request merged**
