### PR TITLE
New Pattern Submission: AWS API Gateway IAM authorization and AWS v4 request signing (sls & Python)

### PR DESCRIPTION
**Pull request by bb245**
*Issue #, if available:* https://github.com/aws-samples/serverless-patterns/issues/2045

*Description of changes:*

This pattern involves employing an AWS_IAM authorizer to secure an API endpoint through Python 3 and the Serverless framework. It illustrates the process of signing the HTTP request using IAM credentials and adhering to the [AWS v4 signing process](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-signing.html). This ensures access to the protected endpoint from a public API. The interaction with APIs is facilitated by AWS API Gateway.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bb245** [comment]
@cornelcroi @bls20AWS fyi, moved the PR from draft to review.

**Comment by bb245** [comment]
@cornelcroi @bls20AWS fyi, description ahould meet maximum length of 150 restriction.

**Comment by bb245** [comment]
@cornelcroi @bls20AWS FYI, the description char limit is fixed.

**Comment by cornelcroi** [comment]
Hi @bb245,

I've reviewed the code and tried to understand from the readme what is the purpose of the pattern and here are my remarks:

- the workflow is not easy to understand from the diagram
- you are showing basically how a lambda calls another lambda through a public API GW endpoint (protected using AWS_IAM) but this an anti pattern (especially in your case where you have the same API GW in front of both Lambdas).
I imagine your purpose was to show how to sign a request but in this implementation it makes an anti pattern.

I suggest you find another implementation to demonstrate how to sign requests.

**Comment by bb245** [comment]
@cornelcroi I’ll get back with a different implementation. This is to demonstrate aws v4 signing process to call the api aws_iam auth. I got deviated from the fundamentals in order to keep it simple.

**Comment by bb245** [comment]
Hi @cornelcroi, could you please review the updated codebase whenever you have a moment.

**Comment by bb245** [comment]
Hi @cornelcroi, could you please review the updated codebase whenever you have a moment. Thanks.

**Comment by bb245** [comment]
Hi @cornelcroi, can you please review the updated codebase whenever you have a moment? Thanks.

**Comment by bb245** [comment]
Hi @cornelcroi, I update the implementation & request your review. Thank you.

**Comment by cornelcroi** [comment]
Hi @bb245,

Thanks for the update.
The diagram now looks much better, easy to understand.
However in your pattern you make a call from a Lambda function to another Lambda function through an API Gateway endpoint which is still an anti pattern. 
We will not be able to put this pattern on ServerlessLand.
If you come across another scenario where signing a request proves beneficial while adhering to a serverless pattern, we would be pleased to examine it.

**Pull request closed without merging**
