### PR TITLE
systems-manager-to-stepfunction to main

### PR DESCRIPTION
**Pull request by lalit21984**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by singledigit — CHANGES_REQUESTED** [review]
This is missing the `example-pattern.json` template. Please include and update PR

**Comment by lalit21984** [comment]
added pattern.json file in the repo.

**Comment by singledigit** [comment]
@lalit21984 This is still missing the example-pattern.json file. Please make sure this file exists in the root directory and should be called `example-pattern.json`. This is necessary for automated pre-merge tests.

**Comment by lalit21984** [comment]
thanks @singledigit , I have renamed the file to example-pattern.json

**Comment by singledigit** [comment]
This is still failing validation. The error is `RDS instance master username must not be a plaintext string or a Ref to a Parameter with a Default value.  Can be Ref to a NoEcho Parameter without a Default, or a dynamic reference to a secretsmanager value` . Please refactor.

**Comment by lalit21984** [comment]
@singledigit I have update the template for secretmanager

**Comment by lalit21984** [comment]
@singledigit I have updated the code for secrets-manager, can you please re-ran the validation

**Comment by lalit21984** [comment]
@singledigit Could you please run the validation. I have already made the changes as per your comments.

**Comment by singledigit** [comment]
This is still failing. Error `RDS instance master username must not be a plaintext string or a Ref to a Parameter with a Default value.  Can be Ref to a NoEcho Parameter without a Default, or a dynamic reference to a secretsmanager value.` You refactored the password but not the user name. Please update.

**Comment by lalit21984** [comment]
@singledigit  ok i have referenced masterusername as well to a SecretManager.

**Comment by singledigit** [comment]
image

Hey @lalit21984 I merged this but have found issues in the README that I cannot figure out how to fix. This is the testing instructions. The JSON seems invalid and the formatting is incorrect. Please submit a new PR with the fixes.

**Pull request merged**
