### PR TITLE
New serverless pattern - lambda-eventbridge_scheduler-cdk

### PR DESCRIPTION
**Pull request by shaniru-aws**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pputhran** [comment]
@shaniru-aws, can you please check the above message and add the example-pattern.json file?

**Comment by pputhran** [comment]
@shaniru-aws Any updates?

**Comment by shaniru-aws** [comment]
I will update by tomorrow.

**Comment by shaniru-aws** [comment]
@pputhran Added example-pattern.json file.

**Comment by shaniru-aws** [comment]
@pputhran any updates on this ?

**Review by pputhran — APPROVED** [review]

**Pull request merged**
