### PR TITLE
New serverless pattern - AWS Lambda to AWS Secrets Manager

### PR DESCRIPTION
**Pull request by PankajRawat333**
*Issue #, if available:*

*Description of changes:* A new pattern is added in the folder lambda-vpc-endpoints-secrets-manager-cdk-dotnet

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jbesw** [comment]
Thanks! This will be live at https://serverlessland.com/patterns/lambda-secretsmanager-dotnet-cdk shortly.

**Comment by PankajRawat333** [comment]
Hi @jbesw Thanks for merging PR. 

The diagram does not look what I am trying to achieve through this pattern, could you please add **Lambda function inside VPC** and show **VPC endpoints** to connect with AWS Secrets manager.

**Comment by PankajRawat333** [comment]
Hi @jbesw I want this pattern diagram to look like https://rawatpankaj.com/posts/images/Lambda-vpc-endpoints-secrets-manager.jpg

**Comment by jbesw** [comment]
Sorry, this has now been updated.

**Pull request merged**
