### PR TITLE
New serverless pattern - apigw-sns-sms

### PR DESCRIPTION
**Pull request by jhsiddhi**
*Issue #, if available:*

*Description of changes:* API Gateway integration with SNS SMS to send transactional SMS messages.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jbesw** [comment]
Picking this up for testing/merging.

**Comment by jbesw** [comment]
Thanks for the contribution! This will be live at https://serverlessland.com/patterns/apigw-sqs-sms-sam soon.

**Comment by jhsiddhi** [comment]
The link https://serverlessland.com/patterns/apigw-sqs-sms-sam is not pointing to the template I have published. Can you please try again? Mine should have a link like this: https://serverlessland.com/patterns/apigw-sns-sms

**Comment by boyney123** [comment]
Thanks @jhsiddhi, I found the issue just fixed it. Thanks for letting us know, and the contribution!

This is live here: [serverlessland.com/patterns/apigw-sns-sms](https://serverlessland.com/patterns/apigw-sns-sms)

**Pull request merged**
