### PR TITLE
[Follow up PR] New pattern submission: Lambda Elastic IP without NAT Gateway

### PR DESCRIPTION
**Pull request by MohamadSoufan**
*Issue #, if available:  #1642*

*Description of changes:*

Removed the function name from the filter
Added documentation

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

This is a follow up PR to [this PR](https://github.com/aws-samples/serverless-patterns/pull/1644)

### CODE REVIEW

**Comment by MohamadSoufan** [comment]
Hello @mavi888  this is a follow-up PR to [this PR](https://github.com/aws-samples/serverless-patterns/pull/1644)
I want to draw your attention to the that this pattern page hasn't yet been populated [checkout here](https://serverlessland.com/patterns/lambda-elastic-ip-no-nat-gateway-cdk) 
it is just a blank white page... Did we make a mistake in the documentation?

**Comment by jbesw** [comment]
For #1644, the pattern is now live at https://serverlessland.com/patterns/lambda-elastic-ip-no-nat-gateway-cdk.

**Comment by MohamadSoufan** [comment]
> For #1644, the pattern is now live at https://serverlessland.com/patterns/lambda-elastic-ip-no-nat-gateway-cdk.

Thank you very much, James,

We are publicly advertising this new pattern on LinkedIn

**Comment by MohamadSoufan** [comment]
> @MohamadSoufan looks like you are missing the example-pattern.json file in your pattern.
> 
> You can [find the example-pattern template here](https://github.com/aws-samples/serverless-patterns/blob/main/_pattern-model/example-pattern.json).
> 
> The file is used on ServerlessLand and is required. Once the file is added we can review the pattern.

There is an example pattern.json file in this pattern

This is a follow up PR on a previous one

**Comment by MohamadSoufan** [comment]
@mavi888 @jbesw @ can we merge this PR?

**Pull request merged**
