### PR TITLE
New serverless pattern - apigw-rest-api-lambda-ecr

### PR DESCRIPTION
**Pull request by ramvijai**
*Issue #, if available:*

*Description of changes:* New serverless pattern to deploy ASP.NET Core Web API (.NET 6) to AWS Lambda as Container Image.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ramvijai** [comment]
@mavi888 Please let me know if there are any review comments or changes required for this PR.Thanks

**Comment by mavi888** [comment]
Hello,
Thanks for submitting this patter. After running the patter following the instructions I get a 502 when accessing the url. 

Can you fix this problem and then i can keep on reviewing the PR

Thanks a lot!

**Comment by ramvijai** [comment]
Hi,

Thanks for your comment. I executed the same steps in another region also and I am able to access the link without any issues. Please find the screenshot below. 
image

**Comment by mavi888** [comment]
I followed the steps and I get the same error. 
Maybe you have some prerequisites or something installed in your computer that is not listed in the pr. 
Screenshot 2023-04-25 at 10 03 05

**Comment by jbesw** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
