### PR TITLE
New serverless pattern - EventBridge Pipe - SQS to EventBus to Lambda and SQS

### PR DESCRIPTION
**Pull request by vinodkrishnaa**
*Issue #, if available:*

*Description of changes:*
This pattern uses SQS and triggers EventBridge events which is routed to multiple targets, SQS and Lambda

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jbesw** [comment]
Your example-pattern.json file has failed validation - please fix this and we will reevaluate the submission.

**Comment by jbesw** [comment]
Your example-pattern.json file has failed validation - please fix this and we will reevaluate the submission.

**Comment by boyney123** [comment]
Seems like loads of files in the pull request @vinodkrishnaa? Is something missing from your git ignore file?

**Comment by vinodkrishnaa** [comment]
I have added git ignore, please review

**Pull request closed without merging**
