### PR TITLE
CDK project to authenticate API using Cognito client credentials flow

### PR DESCRIPTION
**Pull request by suhasini-udayar**
- cdk project for cognito authenticated api

*Issue #, if available:*

*Description of changes:*

CDK TypeScript project for APG pattern [service to service call using Cognito client credentials flow](https://apg-library.amazonaws.com/content-viewer/author/8567548d-91a4-409f-a3cd-25560b0a07c7)

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by suhasini-udayar** [comment]
> @suhasini-udayar looks like you are missing the example-pattern.json file in your pattern.
> 
> You can [find the example-pattern template here](https://github.com/aws-samples/serverless-patterns/blob/main/_pattern-model/example-pattern.json).
> 
> The file is used on ServerlessLand and is required. Once the file is added we can review the pattern.

Hello, I have added the example-pattern.json as suggested. Please let me know if you need any other info. Thanks.

**Comment by suhasini-udayar** [comment]
@boyney123 , may I please request someone to review this PR? I have added the example-pattern template. Please let me know if you need any other info. Thanks.

**Comment by suhasini-udayar** [comment]
@boyney123 , please let me know if I need to make any changes. Thanks!

**Review by singledigit — APPROVED** [review]

**Comment by singledigit** [comment]
@suhasini-udayar the repo is missing the actual lib folder with the code. Can you please fix and do a new PR? I didn't realize that before I merged.

**Comment by suhasini-udayar** [comment]
@singledigit , I missed it too. Will submit a new PR shortly. Thanks!

**Comment by suhasini-udayar** [comment]
@singledigit , here is the PR for lib - https://github.com/aws-samples/serverless-patterns/pull/916
Thanks again!

**Pull request merged**
